### ISSUE TITLE
"--no-progress" option

### ISSUE THREAD

**Issue by jdcrensh** [avaragado/riw#10]
We use this tool in CI (via module api, not cli). It would be nice if there was a way to disable the status bar output, since when not run in an interactive context, it floods the logs with filename output.

**Comment by avaragado** [comment]
Can you explain more about how you run riw in CI?

Used programmatically, as described (poorly) in https://github.com/avaragado/riw/blob/master/doc/library.md, calling `riw.app.translate()` outputs nothing.

It sounds as though you're running `riw app translate` from within your CI config. Is that right?

**Comment by avaragado** [comment]
ping @jdcrensh

**Comment by avaragado** [comment]
I've released riw v0.8.0 which adds `riw app translate --quiet`

**Comment by jdcrensh** [comment]
hey @avaragado. awesome, i'll give the new version a shot.

i believe the api method we're using that shows the status bar output is `riw.app.import()`, does v0.8.0  cover that as well?

**Comment by jdcrensh** [comment]
@avaragado how can `--quiet` be used directly (i.e. not through the CLI)? example of how we're using it as an API:

```js
const fs = require('fs-extra');
const { paths } = require('./common');
const config = paths.riwConfig; // ie: src/locale/riw-db.json

const riw = {
  app: {
    translate: require('riw/dist/bin/commands/app-commands/translate').handler,
  },
  db: {
    import: require('riw/dist/bin/commands/db-commands/import').handler,
    init: require('riw/dist/bin/commands/db-commands/init').handler,
  },
};

const groupValidity = tr =>
  tr.defaultMessage && tr.locale && tr.translation ? 'valid' : 'invalid';

module.exports = {
  app: {
    translate: () => {
      riw.app.translate({ config });
    },
  },
  db: {
    init: () => {
      riw.db.init({ config });
    },
    import: () => {
      const translations = fs.readJsonSync(paths.riwTodo); // ie: src/locale/TODO-untranslated.json
      const file = { valid: [], invalid: [] };
      for (const t of translations) {
        file[groupValidity(t)].push(t);
      }
      riw.db.import({ config, file });
    },
  },
};

// usage:
const riw = require('./riw');
riw.db.import();
riw.app.translate();
```

**Comment by avaragado** [comment]
Ah, you're calling the CLI handlers directly. I wouldn't recommend this.

The riw module exports a function `createRIW`. Use that to create a `riw` instance, on which you can call `riw.app.translate()` and `riw.db.update({ translations })`, where `translations` is an array of valid `{ defaultMessage, description, locale, translation }`.

See https://github.com/avaragado/riw/blob/master/doc/library.md - I'm sorry the doc for this usage is so bad. I'll try to expand it soon.
