### ISSUE TITLE
TypeScript support via a transpile hook?

### ISSUE THREAD

**Issue by roosmaa** [avaragado/riw#11]
I just added `riw` to a project I'm contributing to. (@avaragado - awesome work, thank you for making this! :clap:) It's a TypeScript project, so right now there's a transpile-to-JS step that needs to happen before babel (invoked by riw) can extract the strings for localisation.

Since manually invoking the transpilation can easily be forgotten, I was wondering ... if there would be interest in a pre-babel hook implementation in riw that could be configured to run such transpile step automatically? If so I could contribute that in the near future.

Something in the following direction:

```
/* package.json */
{
  "riw": {
      "transpileCommand": "tsc -p . --target ES6 --module esnext --jsx preserve --outDir tmp/transpiled",
      "sourceDirs": [
        "tmp/transpiled/**/*.js",
        "tmp/transpiled/**/*.jsx"
      ]
   }
}
```

**Comment by avaragado** [comment]
@roosmaa That sounds reasonable to me. I'd be happy to consider any pull request!

**Comment by roosmaa** [comment]
I'll just close this for now as the time slot I had planned for this came and went. Maybe down the line I'll open a PR with this :)
