### ISSUE TITLE
Use relative paths in TODO file

### ISSUE THREAD

**Issue by jdcrensh** [avaragado/riw#5]
The file names in `TODO-untranslated.json` are output as an absolute path. It should use the relative path from the app's root so that the file can be shared among developers.

**Comment by avaragado** [comment]
You're right. I'll hopefully take a look at this tomorrow, day job permitting. Thanks for the report!

**Comment by avaragado** [comment]
I've released 0.6.1 which I believe fixes this.

**Comment by jdcrensh2** [comment]
@avaragado upgraded and it works great, thanks!

**Comment by jdcrensh** [comment]
@avaragado upgraded and it works great, thanks!
